insert into Task (title, description, points) values ('Diamond Dogs', 'Oth nondisp fx of sixth cervcal vert, subs for fx w nonunion', 1169);
insert into Task (title, description, points) values ('Cleaner', 'Unspecified open wound of unspecified shoulder', 4381);
insert into Task (title, description, points) values ('Marvin''s Room', 'Other specified arthritis, other site', 4904);
insert into Task (title, description, points) values ('Beyond Silence (Jenseits der Stille)', 'Other subluxation of left ulnohumeral joint, subs encntr', 2731);
insert into Task (title, description, points) values ('Boat That Rocked, The (a.k.a. Pirate Radio)', 'Oth personal risk factors, not elsewhere classified', 2975);
insert into Task (title, description, points) values ('Dakota', 'Malignant neoplasm of parotid gland', 782);
insert into Task (title, description, points) values ('Holy Girl, The (Niña santa, La)', 'Chronic gout due to renal impairment, unsp hip, with tophus', 502);
insert into Task (title, description, points) values ('Paranoia Agent', 'Burn of unspecified degree of right palm', 2338);
insert into Task (title, description, points) values ('Ip Man: The Final Fight', 'Contusion of eyeball and orbital tissues, right eye, subs', 1771);
insert into Task (title, description, points) values ('Fog City Mavericks', 'Underdosing of other hormone antagonists, sequela', 1073);
insert into Task (title, description, points) values ('Today You Die', 'Unsp mtrcy rider injured in clsn w 2/3-whl mv nontraf, init', 1315);
insert into Task (title, description, points) values ('Waxwork', 'Pemphigoid, unspecified', 2561);
insert into Task (title, description, points) values ('Dirty Carnival, A (Biyeolhan geori)', 'Symptomatic premature menopause', 665);
insert into Task (title, description, points) values ('Shanghai Express', 'Leakage of surgically created arteriovenous fistula, sequela', 1267);
insert into Task (title, description, points) values ('Sherlock Holmes: A Game of Shadows', 'Polyhydramnios, unspecified trimester, fetus 5', 480);
insert into Task (title, description, points) values ('Hamlet', 'Strain of unsp musc/fasc/tend at shldr/up arm, unsp arm', 118);
insert into Task (title, description, points) values ('Modify ', 'Lateral disloc of proximal end of tibia, unsp knee, sequela', 4435);
insert into Task (title, description, points) values ('Mountain Men, The', 'Displaced pilon fx r tibia, subs for clos fx w delay heal', 4513);
insert into Task (title, description, points) values ('Boxing Helena', 'Congenital malformations of aortic and mitral valves', 3424);
insert into Task (title, description, points) values ('Last Hurrah for Chivalry (Hao xia)', 'Osteolysis, forearm', 4751);
insert into Task (title, description, points) values ('Monkey in Winter, A (Un singe en hiver)', 'Incorrect dilution of fluid used during infusion', 3326);
insert into Task (title, description, points) values ('Attack of the 50 Foot Woman', 'Oth specific joint derangements of unsp elbow, NEC', 1495);
insert into Task (title, description, points) values ('Judgment in Berlin', 'Nonpurulent mastitis associated with lactation', 4411);
insert into Task (title, description, points) values ('Welcome to the Dollhouse', 'Minor laceration of right internal jugular vein, subs encntr', 926);
insert into Task (title, description, points) values ('Big Pun: The Legacy', 'Burn of second degree of trunk, unsp site, init encntr', 670);
insert into Task (title, description, points) values ('Everybody''s Acting', 'Fracture of subcondylar process of left mandible, 7thB', 4425);
insert into Task (title, description, points) values ('Masque of the Red Death, The', 'Malignant carcinoid tumor of the sigmoid colon', 4331);
insert into Task (title, description, points) values ('Spirit, The', 'Asphyxiation due to smothering in furniture, self-harm, init', 4302);
insert into Task (title, description, points) values ('Pure Luck', 'Maternal care for unstable lie, not applicable or unsp', 1989);
insert into Task (title, description, points) values ('One and Only, The (Eneste ene, Den)', 'Pathological fracture in neoplastic disease, unsp hand, init', 4350);
